version: 2.1

jobs:
  build_and_deploy:
    docker:
      - image: cimg/go:1.22.2
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.16
      - run:
          name: Install Node.js and pnpm
          command: |
            curl -sL https://deb.nodesource.com/setup_20.x | sudo bash -
            sudo apt-get install -y nodejs
            sudo corepack enable
            sudo corepack prepare pnpm@latest --activate
      - run:
          name: Build frontend
          command: |
            cd web
            pnpm i --frozen-lockfile
            pnpm build
      - run:
          name: Build backend
          command: CGO_ENABLED=0 go build -o memos ./bin/memos/main.go
      - run:
          name: Build Docker image
          command: |
            docker build -t your-username/memos:${CIRCLE_SHA1} .
      - run:
          name: Push Docker image
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push your-username/memos:${CIRCLE_SHA1}
      - deploy:
          name: Shippy-it!
          command: ./scripts/deploy_script.sh

workflows:
  version: 2
  build_deploy:
    jobs:
      - build_and_deploy:
          filters:
            branches:
              only:
                - main